# Generated by Django 3.2.5 on 2021-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
